<?php

namespace Database\Seeders;

use App\Models\Movie;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class MovieSeeder extends Seeder
{
    public function run(): void
    {
        $movies = [
            [
                'title' => 'Oppenheimer',
                'description' => 'De geschiedenis van J. Robert Oppenheimer en zijn rol in de ontwikkeling van de atoombom. Een meeslepend biografisch drama over een van de meest invloedrijke wetenschappers van de 20e eeuw.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=uYPbbksJxIg',
                'genre' => 'Biografie',
                'age_rating' => 12,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 180,
                'release_date' => Carbon::parse('2023-07-21'),
            ],
            [
                'title' => 'Barbie',
                'description' => 'Barbie en Ken beleven het beste leven in het kleurrijke Barbieland. Als ze de kans krijgen om naar de echte wereld te gaan, ontdekken ze dat perfectie niet alleen aan de buitenkant zit.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=pBk4NYhWNMM',
                'genre' => 'Komedie',
                'age_rating' => 6,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 114,
                'release_date' => Carbon::parse('2023-07-21'),
            ],
            [
                'title' => 'The Batman',
                'description' => 'Batman moet een seriemoordenaar stoppen die het op de elite van Gotham City heeft gemunt. Een duistere detective thriller waarin de Dark Knight zijn eerste jaren als misdaadbestrijder doorstaat.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
                'genre' => 'Actie',
                'age_rating' => 12,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 176,
                'release_date' => Carbon::parse('2022-03-04'),
            ],
            [
                'title' => 'Avatar: The Way of Water',
                'description' => 'Jake Sully en Neytiri zijn ouders geworden. Maar het geluk is van korte duur als een oude vijand terugkeert naar Pandora. De familie Sully moet vluchten naar een waterwereld vol nieuwe wezens.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=d9MyW72ELq0',
                'genre' => 'Sci-Fi',
                'age_rating' => 12,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 192,
                'release_date' => Carbon::parse('2022-12-16'),
            ],
            [
                'title' => 'Inception',
                'description' => 'Een dief die bedreven is in de gevaarlijke kunst van extractie - het stelen van waardevolle geheimen vanuit het onderbewustzijn - krijgt een kans op verlossing als hij een onmogelijke taak volbrengt.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
                'genre' => 'Sci-Fi',
                'age_rating' => 12,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 148,
                'release_date' => Carbon::parse('2010-07-16'),
            ],
            [
                'title' => 'Dune',
                'description' => 'Een briljante en begaafde jonge man wordt geboren met een grote toekomst die verder reikt dan wat hij begrijpt. Hij moet naar de gevaarlijkste planeet in het universum reizen.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=8g18jFHCLXk',
                'genre' => 'Sci-Fi',
                'age_rating' => 12,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 155,
                'release_date' => Carbon::parse('2021-10-22'),
            ],
            [
                'title' => 'Spider-Man: No Way Home',
                'description' => 'Voor het eerst in de filmische geschiedenis wordt Spider-Mans identiteit onthuld. Peter Parker vraagt Doctor Strange om hulp, maar de betovering veroorzaakt een ramp die alles verandert.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
                'genre' => 'Actie',
                'age_rating' => 12,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 148,
                'release_date' => Carbon::parse('2021-12-17'),
            ],
            [
                'title' => 'Top Gun: Maverick',
                'description' => 'Na meer dan dertig jaar dienst keert de iconische Top Gun terug waar hij thuishoort. Pete "Maverick" Mitchell moet de beste piloten van de marine trainen voor een gevaarlijke missie.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=qSqVVswa420',
                'genre' => 'Actie',
                'age_rating' => 12,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 131,
                'release_date' => Carbon::parse('2022-05-27'),
            ],
            [
                'title' => 'The Super Mario Bros. Movie',
                'description' => 'Een loodgieter genaamd Mario reist door een ondergrondse doolhof met zijn broer Luigi, in een poging om een gevangen prinses te redden. Een kleurrijk animatie-avontuur vol humor en actie.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=TnGl01FkMMo',
                'genre' => 'Animatie',
                'age_rating' => 6,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 92,
                'release_date' => Carbon::parse('2023-04-05'),
            ],
            [
                'title' => 'Guardians of the Galaxy Vol. 3',
                'description' => 'Peter Quill moet zijn team verzamelen om een gevaarlijke missie uit te voeren. Als de missie niet succesvol wordt voltooid, kan dit wel eens het einde van de Guardians betekenen.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=u3V5KDHRQvk',
                'genre' => 'Actie',
                'age_rating' => 12,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 150,
                'release_date' => Carbon::parse('2023-05-05'),
            ],
            [
                'title' => 'The Equalizer 3',
                'description' => 'Robert McCall vindt een nieuwe thuis in Zuid-Italië. Als zijn vrienden worden bedreigd door lokale misdaad, weet hij wat hij moet doen: zijn vrienden beschermen.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=19ikjeJXPyI',
                'genre' => 'Actie',
                'age_rating' => 16,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 109,
                'release_date' => Carbon::parse('2023-08-30'),
            ],
            [
                'title' => 'The Little Mermaid',
                'description' => 'De jonge zeemeermin Ariel is gefascineerd door de wereld boven water. Tegen de wil van haar vader sluit ze een deal om haar dromen waar te maken, maar brengt daarmee ook haar leven in gevaar.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=kpGo2_d3oYE',
                'genre' => 'Familie',
                'age_rating' => 6,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 135,
                'release_date' => Carbon::parse('2023-05-26'),
            ],
            [
                'title' => 'Mission: Impossible - Dead Reckoning',
                'description' => 'Ethan Hunt en zijn IMF-team moeten een nieuwe dodelijke wapen opsporen voordat het in verkeerde handen valt. Een gevaarlijke missie vol spectaculaire stunts en wendingen.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=avz06PDqDbM',
                'genre' => 'Actie',
                'age_rating' => 12,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 163,
                'release_date' => Carbon::parse('2023-07-12'),
            ],
            [
                'title' => 'Elemental',
                'description' => 'In een stad waar vuur-, water-, aarde- en luchtbewoners samenleven, ontmoet een vurig meisje een relaxte jongen. Samen ontdekken ze hoeveel ze gemeen hebben.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=hXzcyx9V0xw',
                'genre' => 'Animatie',
                'age_rating' => 6,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 101,
                'release_date' => Carbon::parse('2023-06-16'),
            ],
            [
                'title' => 'John Wick: Chapter 4',
                'description' => 'John Wick ontdekt een weg naar het verslaan van The High Table. Maar voordat hij zijn vrijheid kan verdienen, moet hij het opnemen tegen een nieuwe vijand met krachtige allianties.',
                'poster_image' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=qEVUtrk8_B4',
                'genre' => 'Actie',
                'age_rating' => 16,
                'language' => 'Engels',
                'country' => 'Verenigde Staten',
                'duration' => 169,
                'release_date' => Carbon::parse('2023-03-24'),
            ],
        ];

        foreach ($movies as $movie) {
            Movie::create($movie);
        }
    }
}
